Make configuration a little less dependant on Sentry being set up
steamclock/steamclog-swift pull request #104
Opened 2022-03-21 17:16 UTC by brendanlensink

While Sentry should still be our default logging library, we're likely to have clients that want to use different SDKs instead.

The current version of SteamcLog works without a Sentry key, it's kind of weird and logs a warning to the console the first time you try and log something.

This PR changes that by:
- Moving any sentry specific config options out of `Config` and into a new `SentryConfig` object
- Adds a new parameters to the SteamcLog `init`: `sentryConfig: SentryConfig?`. If you set this to `nil`, Sentry and the `SentryDestination` aren't created when setting everything else up

Version number:
This bumps the version number up to 2.0.0. I think given this changes the main SteamcLog constructor, it makes sense to bump the major version number. I'm not married to this however, and would be curious if anyone feels like 1.1.0 would be more appropriate.

2022-03-22 20:43 UTC, JeremyChiang requested changes
Everything looks good to me, but I would just like to suggest adding 1 more thing:

I think we should add `tracesSampleRate` to the config as well. We can default it to zero, but I think as we learn and practice more with Sentry's performances metrics, we may want to re-enable it in some larger and busier projects.

2022-03-23 21:59 UTC, jenncoop approved these changes
Looks good!

Yeah, this is breaking as the core API is changed, so I agree with your choice of bumping the major version 🚀

2022-03-23 21:59 UTC, jenncoop commented on SteamcLog/Classes/SteamcLog.swift
> +                options.tracesSampleRate = 0.0
Yeah, agreed with Jeremy that we should move this one into the Sentry config. I should've done this when I made this change last week.

2022-03-23 22:20 UTC, brendanlensink commented
Good call Jeremy! Updated.

2022-03-25 17:14 UTC, JeremyChiang approved these changes
Great work! :shipit:

2022-03-25 17:15 UTC, merged